// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/protobuf/AwesomePowerUp.proto

package com.thecodeslinger.ppjs.proto;

public final class AwesomePowerUpOuterClass {
  private AwesomePowerUpOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AwesomePowerUpOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.thecodeslinger.ppjs.proto.AwesomePowerUp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 level = 2;</code>
     * @return The level.
     */
    int getLevel();
  }
  /**
   * Protobuf type {@code com.thecodeslinger.ppjs.proto.AwesomePowerUp}
   */
  public static final class AwesomePowerUp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.thecodeslinger.ppjs.proto.AwesomePowerUp)
      AwesomePowerUpOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AwesomePowerUp.newBuilder() to construct.
    private AwesomePowerUp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AwesomePowerUp() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AwesomePowerUp();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AwesomePowerUp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              level_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.internal_static_com_thecodeslinger_ppjs_proto_AwesomePowerUp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.internal_static_com_thecodeslinger_ppjs_proto_AwesomePowerUp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.AwesomePowerUp.class, com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.AwesomePowerUp.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LEVEL_FIELD_NUMBER = 2;
    private int level_;
    /**
     * <code>int32 level = 2;</code>
     * @return The level.
     */
    @java.lang.Override
    public int getLevel() {
      return level_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (level_ != 0) {
        output.writeInt32(2, level_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (level_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, level_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.AwesomePowerUp)) {
        return super.equals(obj);
      }
      com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.AwesomePowerUp other = (com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.AwesomePowerUp) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (getLevel()
          != other.getLevel()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getLevel();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.AwesomePowerUp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.AwesomePowerUp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.AwesomePowerUp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.AwesomePowerUp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.AwesomePowerUp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.AwesomePowerUp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.AwesomePowerUp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.AwesomePowerUp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.AwesomePowerUp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.AwesomePowerUp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.AwesomePowerUp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.AwesomePowerUp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.AwesomePowerUp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.thecodeslinger.ppjs.proto.AwesomePowerUp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.thecodeslinger.ppjs.proto.AwesomePowerUp)
        com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.AwesomePowerUpOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.internal_static_com_thecodeslinger_ppjs_proto_AwesomePowerUp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.internal_static_com_thecodeslinger_ppjs_proto_AwesomePowerUp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.AwesomePowerUp.class, com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.AwesomePowerUp.Builder.class);
      }

      // Construct using com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.AwesomePowerUp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        level_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.internal_static_com_thecodeslinger_ppjs_proto_AwesomePowerUp_descriptor;
      }

      @java.lang.Override
      public com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.AwesomePowerUp getDefaultInstanceForType() {
        return com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.AwesomePowerUp.getDefaultInstance();
      }

      @java.lang.Override
      public com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.AwesomePowerUp build() {
        com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.AwesomePowerUp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.AwesomePowerUp buildPartial() {
        com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.AwesomePowerUp result = new com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.AwesomePowerUp(this);
        result.name_ = name_;
        result.level_ = level_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.AwesomePowerUp) {
          return mergeFrom((com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.AwesomePowerUp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.AwesomePowerUp other) {
        if (other == com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.AwesomePowerUp.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getLevel() != 0) {
          setLevel(other.getLevel());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.AwesomePowerUp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.AwesomePowerUp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int level_ ;
      /**
       * <code>int32 level = 2;</code>
       * @return The level.
       */
      @java.lang.Override
      public int getLevel() {
        return level_;
      }
      /**
       * <code>int32 level = 2;</code>
       * @param value The level to set.
       * @return This builder for chaining.
       */
      public Builder setLevel(int value) {
        
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 level = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLevel() {
        
        level_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.thecodeslinger.ppjs.proto.AwesomePowerUp)
    }

    // @@protoc_insertion_point(class_scope:com.thecodeslinger.ppjs.proto.AwesomePowerUp)
    private static final com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.AwesomePowerUp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.AwesomePowerUp();
    }

    public static com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.AwesomePowerUp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AwesomePowerUp>
        PARSER = new com.google.protobuf.AbstractParser<AwesomePowerUp>() {
      @java.lang.Override
      public AwesomePowerUp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AwesomePowerUp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AwesomePowerUp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AwesomePowerUp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.thecodeslinger.ppjs.proto.AwesomePowerUpOuterClass.AwesomePowerUp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_thecodeslinger_ppjs_proto_AwesomePowerUp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_thecodeslinger_ppjs_proto_AwesomePowerUp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n0src/main/resources/protobuf/AwesomePow" +
      "erUp.proto\022\035com.thecodeslinger.ppjs.prot" +
      "o\"-\n\016AwesomePowerUp\022\014\n\004name\030\001 \001(\t\022\r\n\005lev" +
      "el\030\002 \001(\005b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_thecodeslinger_ppjs_proto_AwesomePowerUp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_thecodeslinger_ppjs_proto_AwesomePowerUp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_thecodeslinger_ppjs_proto_AwesomePowerUp_descriptor,
        new java.lang.String[] { "Name", "Level", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
